title: Git and GitHub first-timers
description: A learning path for GitHub first-timers.
steps:
  - link: 'https://youtube.com/watch?v=w3jLJU7DT5E'
    video: 'https://youtube.com/embed/w3jLJU7DT5E'
    title: 'Video: What is GitHub?'
    description: >-
      Someone told you to use Git and GitHub? Awesome! Let's find out what is
      GitHub in this short video.
  - link: 'https://guides.github.com/introduction/flow/'
    title: Understanding the GitHub flow
    description: >-
      GitHub flow is a lightweight, branch-based workflow that supports teams
      and projects where deployments are made regularly. This guide explains how
      and why GitHub flow works.
  - title: What's a repository?
    video: 'https://www.youtube.com/embed/UmX4kyB2wfg'
    description: >-
      In this video, you will learn how to find the key pages and features we
      will be using throughout this course.
    link: 'https://www.youtube.com/watch?v=UmX4kyB2wfg'
  - course: githubtraining/introduction-to-github
  - title: Git Handbook
    description: >-
      By now you are probably wondering what a Git is and why it is important in
      writing code. Take a look at this short article on version control with
      Git.
    link: 'https://guides.github.com/introduction/git-handbook/'
  - course: githubtraining/communicating-using-markdown
  - title: Connecting to GitHub with SSH
    description: >-
      Using the SSH protocol, you can connect and authenticate to remote servers
      and services.
    link: >-
      https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
  - title: Getting a Git Repository
    description: 'If you want to get a copy of an existing Git repository, read this guide.'
    link: >-
      https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository#_git_cloning
  - title: Git Push and Pull
    video: 'https://www.youtube.com/embed/-uQHV9GOA0w'
    description: >-
      Working locally has an interesting challenge of keeping the remote and
      local repositories update. Git pull and git push are network commands to
      help.
    link: 'https://www.youtube.com/watch?v=-uQHV9GOA0w'
  - course: githubtraining/managing-merge-conflicts
